### ISSUE TITLE
Automatic tuning

### ISSUE THREAD

**Issue by romainbrette** [romainbrette/clampy#4]
We need some methods to automatically adjust bridge and voltage-clamp tunings.

**Comment by romainbrette** [comment]
What can be automated:
* Capacitance neutralization (current-clamp or I=0)
* TEVC: loop gain, loop lag ()

First step:
* Increase capacitance
* Measure voltage trace
* Look at what changes: increased variance? or oscillations?

**Comment by romainbrette** [comment]
For the TEVC, there's a [PID autotuning](https://github.com/hirschmann/pid-autotune) library we might be able to use. A classic rule is [Ziegler-Nichols](https://en.wikipedia.org/wiki/Ziegler%E2%80%93Nichols_method). It's based on increasing the gain until we see an oscillation, ie just before it becomes unstable. In fact perhaps we can even use the amplifier oscillation detector.

**Comment by romainbrette** [comment]
The Z-N rule is the following: measure the gain G at oscillation and the period T of the oscillation. The tunings are: gain = 0.8*G; phase lag = T/8.

**Comment by huyhoang93** [comment]
Automatic tuning simplified as finding the positive minimum value of the intercept in the regression model, showing robust result to find the capacitance value before oscillation without preset thresholds.
--> Tuned value = 0.5*(value before oscillation)

**Comment by romainbrette** [comment]
I have implemented it with pyautogui. It works simply by using the oscillation detection feature, and bisection. Then selects 0.8*C, where C is the critical capacitance. This should be fine in the bath, maybe not so much in the cell.
